### PR TITLE
When offline stripe is unavailable

### PR DESCRIPTION
**Pull request by mixonic**
The stripe mock should be used when offline.

### CODE REVIEW

**Comment by mixonic** [comment]
Reflecting on this some more: The application may move between offline and online states in a single session. The service should support that, which will probably require more work than this quick patch.

**Comment by buritica** [comment]
I think if you go offline after the fact, we shouldn't mock Stripe and we should let the stripe library error. But I don't mind starting with a mocked version of the library if you're offline, the problem here is if there is a network delay in loading the stripe library we don't want to mock Stripe in production, so this case should be considered. 

In conclusion: we could mock stripe in offline cases if you're testing or in dev environment perhaps, but a store application that expects payments probably doesn't want to mock stripe at any point?

**Comment by JoshSmith** [comment]
I believe this can be closed since #59 will be merged soon.

**Comment by snewcomer** [comment]
This seems to be solved!

**Pull request closed without merging**
