### PR TITLE
Replace Ember.Logger.info with console.log

### PR DESCRIPTION
**Pull request by aliciaphes**
https://github.com/code-corps/ember-stripe-service/issues/61
My Hacktoberfest contribution.

### CODE REVIEW

**Comment by snewcomer** [comment]
@aliciaphes 👋  Would you mind merging master into your branch.  Hopefully the build will pass and we can get this merged!

Ref #65

**Comment by snewcomer** [comment]
@aliciaphes What does `git remote -v` show?  Is there an upstream repo or just origin?

If there is an upstream repo, something like this should work!

```
git checkout master
git pull upstream master --rebase
git checkout replace-with-consolelog
git rebase -i origin/master
git push origin replace-with-consolelog --force
```

If not, you can run `git remote add upstream git@github.com:code-corps/ember-stripe-service.git`

Lmk if you have any questions!  🙇

**Comment by aliciaphes** [comment]
Hi @snewcomer, I am not sure what I'm doing wrong but I don't seem to trigger a successful merge. I followed your steps above and my origin is my forked repo from yours; and my upstream is your repo.
Any other steps that you want me to follow?

**Comment by snewcomer** [comment]
@aliciaphes That's good information!  So if you are just using the command line, hopefully the comments below help a tad 🙏.  

```
git checkout master
  
  # what is the most recent commit according to `git log`?  Is it "Dummy commit, no changes"?

git pull upstream master --rebase
  
  # run `git log` - is the most recent commit "Merge pull request #65 from snewcomer/sn/3.5"?

git push origin master
  
  # this updates your repo to match this repo.  Now ya'll are equal!  But you have a branch with more changes!  So...

git checkout replace-with-consolelog
git merge --no-ff master

  # This updates your branch with changes from the upstream repository (i.e. some new commits since you put this PR up).  save and quit the file if one opens.

git push origin replace-with-consolelog
```

Also, super sorry if you are using a git client as I'm not too familiar with that workflow 😞.  FYI - this article helped me quite a bit - https://hackernoon.com/git-merge-vs-rebase-whats-the-diff-76413c117333

Feel free to reach out again and I will definitely try to help debug this with you!

**Comment by aliciaphes** [comment]
Thanks for this. Triggering a new attempt...

**Comment by snewcomer** [comment]
superseded by #67

**Pull request closed without merging**
